### ISSUE TITLE
Scrolling up discussion shows [deleted] for first post user

### ISSUE THREAD

**Issue by datitisev** [flarum/issue-archive#237]

**Comment by dsevillamartin** [comment]
@matteocontrini Essentially, I think it has to do with the first post of the discussion being loaded but not with its author relationship.

The way Flarum handles relationships is that they must be returned in the API request for them to be seen.

In other words, even if both a post and its author are in the JS store, unless the post has the relationship linking it with the author, `post.user()` will return `false`/`null`. As including relationships in API calls makes them take longer, we usually only request the info we need. Sadly, right now it is not possible to tell the API to only return the relationship (and not the actual referenced model, as for every relationship the API includes - `{ type: 'users', id: 1 }` - it includes the actual model as well `{ type: 'users', id: 1, data: { displayName: '...' } }`.

I also may have just gone on a tangent that has nothing to do with this issue. But I think if there was some way for Flarum to know from the API response who the author ID is, the issue would be resolved as the author is already most likely in the `app.store` (discussion author).

🤔 Feel free to yell at me if nothing I just wrote made sense.

**Comment by matteocontrini** [comment]
> What could help is seeing the HTTP response of the request when this bug occurs. That way we can see the requested data & returned payload.

I've been trying to reproduce the issue for the last 15 minutes... And I couldn't 😕

**Comment by matteocontrini** [comment]
Ah, it seems that this issue was present in the early days (#295) and it was (apparently not) fixed with f3612261ec02e6ea3d15db28451429165657a996 and previously with 6b601ae2d66cea485385d37f5a8c2cfb419c467f.

I'm wondering why the `canEdit` property was chosen for determining whether the post is fully loaded. 🤔

It seems there are still cases when that property is defined but some information is missing. This could also be the cause for the cases when the post likes are not loaded, as reported on Discuss [here](https://discuss.flarum.org/d/24844-sometimes-likes-arent-loaded).

**Comment by dsevillamartin** [comment]
I don't think this would've been fixed with any recent changes. Tried reproducing on discuss, and cannot, but I don't see how this would've been fixed 🤔

**Comment by iPurpl3x** [comment]
Has this been fixed ? Can someone reproduce it ? I could not, but I don't know if I did the right steps to try to reproduce.

**Comment by matteocontrini** [comment]
It still happens, although not necessarily always on the first post as in the original report.

Also, I'm not sure why bug issues weren't kept in the `flarum/framework` repository. Lots of bugs (even reproducible ones) are not being taken into account for this reason...

**Comment by luceos** [comment]
> Also, I'm not sure why bug issues weren't kept in the `flarum/framewory` repository

https://discuss.flarum.org/d/29518-the-clean-slate-method-on-issues-and-pull-requests

Thanks for your understanding.

**Comment by matteocontrini** [comment]
@luceos I actually forgot the part "...after we've pulled issues we feel are important", oops. Apologies for the OT.
